# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f100820dc949cdee8b6464759a6e3c85b5b12c8bc8aab633f75d1633b1070034079b4ab78250d648230839298479ca8d9e2ce9edea15ad82ad2e1e77cc9b84e1

test:
  secret_key_base: 68c30cf47a0cb887096ba0bc8fe0b413446551ad65d6e8e35ff2f87e5773e14e2b132b3e36866526499f23ded6bcf52da7fce30a735ff5271415bef97c3a972c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
